module.exports = {
	preset: "ts-jest",
	transform: { "^.+\\.ts?$": "ts-jest" },
	testEnvironment: "node",
	testRegex: "/src/.*\\.(test|spec)?\\.(ts|tsx)$",
	moduleFileExtensions: ["ts", "tsx", "js", "jsx", "json", "node"],
	moduleNameMapper: {
		"^\\$routes/(.*)$": "<rootDir>/src/routes/$1",
		"^\\$controllers/(.*)$": "<rootDir>/src/controllers/$1",
		"^\\$services/(.*)$": "<rootDir>/src/services/$1",
		"^\\$validations/(.*)$": "<rootDir>/src/validations/$1",
		"^\\$utils/(.*)$": "<rootDir>/src/utils/$1",
		"^\\$entities/(.*)$": "<rootDir>/src/entities/$1",
		"^\\$middlewares/(.*)$": "<rootDir>/src/middlewares/$1",
		"^\\$seeders/(.*)$": "<rootDir>/src/seeders/$1",
		"^\\$config/(.*)$": "<rootDir>/src/config/$1",
		"^\\$pkg/(.*)$": "<rootDir>/src/pkg/$1",
		"^\\$app/(.*)$": "<rootDir>/src/app/$1",
		"^\\$server/(.*)$": "<rootDir>/src/server/$1",
		"^\\$repositories/(.*)$": "<rootDir>/src/repositories/$1",
	},
	// setupFilesAfterEnv: ["<rootDir>/src/jest.setup.js"],
}
