export const PUBSUB_TOPICS = {
    KNOWLEDGE_CREATE: "KNOWLEDGE_CREATE",
    KNOWLEDGE_UPDATE: "KNOWLEDGE_UPDATE",
    KNOWLEDGE_DELETE: "KNOWLEDGE_DELETE",
    ASSIGNMENT_ATTEMPT_SUBMIT: "ASSIGNMENT_ATTEMPT_SUBMIT",
    KNOWLEDGE_APPROVAL_NOTIFICATION: "KNOWLEDGE_APPROVAL_NOTIFICATION",
    ASSIGNMENT_ASSIGNED_NOTIFICATION: "ASSIGNMENT_ASSIGNED_NOTIFICATION",
}
